- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
    private: false #not confidentail
  - name: DURATION
    prompt: please enter the duration
    private: false #not confidentail
  - name: TRAINER
    prompt: please enter the trainer name
    private: false #not confidentail
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"